### ISSUE TITLE
Getting Type error on running command protractor-perf config.js

### ISSUE THREAD

**Issue by anushasridhar15** [axemclion/protractor-perf#27]
Getting below error on using protractor-perf although the browser has been specified in the config file

if (typeof browserConfig[passedBrowser.browserName] !== 'undefined') {
^TypeError: Cannot read property 'browserName' of undefined
at C:\Users\anusha\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\browser-perf\lib\options.js:84:42

NOTE- the code runs perfectly fine with protractor. it also runs when i specify the browser in command line like this ---> protractor-perf config.js --browser=chrome

config file code snippet :--

exports.config={multiCapabilities: [{

browserName:'chrome'

}]
};

**Comment by axemclion** [comment]
@anushasridhar15 This should be fixed with the latest version for browser-perf. Do you still see this error ?

**Comment by aluzardo** [comment]
@axemclion I am getting the same error.

conf.js

```
    multiCapabilities: [
        {
            browserName: 'firefox'
        },
        {
            browserName: 'chrome'
        }
    ],
```

Error log:

```
> protractor-cucumber-tests@1.0.0 test-desktop-local /Users/adolfocabrera/xxx/QA-testing/Selenium/xxx
> protractor-perf conf.js --seleniumAddress 'http://localhost:4444/wd/hub' --params.testUser.username=autobot0

/Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/protractor-perf/node_modules/browser-perf/lib/options.js:84
                        if (typeof browserConfig[passedBrowser.browserName] !== 'undefined') {
                                                              ^

TypeError: Cannot read property 'browserName' of undefined
    at /Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/protractor-perf/node_modules/browser-perf/lib/options.js:84:42
    at Array.forEach (native)
    at opts.accesskey (/Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/protractor-perf/node_modules/browser-perf/lib/options.js:79:18)
    at /Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/protractor-perf/node_modules/browser-perf/lib/options.js:197:10
    at Array.forEach (native)
    at Object.module.exports.scrub (/Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/protractor-perf/node_modules/browser-perf/lib/options.js:196:14)
    at new Runner (/Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/protractor-perf/node_modules/browser-perf/lib/runner.js:12:22)
    at Function.module.exports.getConfig (/Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/protractor-perf/lib/index.js:89:15)
    at Object.<anonymous> (/Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/protractor-perf/lib/cli.js:149:15)
    at Module._compile (module.js:413:34)

```

**Comment by axemclion** [comment]
@jahnavi310 Said that this issue was solved in https://github.com/axemclion/protractor-perf/issues/35
