### ISSUE TITLE
error while running with IE driver

### ISSUE THREAD

**Issue by sanjeevmajgotra** [axemclion/protractor-perf#3]
the package is working as expected when capabilities.browserName:chrome or firefox but it's giving error when its internet explorer.
Please have a look at the stack trace.
Can you give me some pointers what i'm doing wrong?

Error: [execute("(function(){var getTimeMs=(function(){if(window.performance)\nreturn(performance.now||performance.mozNow||performance.msNow||performance.oNow||performance.webkitNow).bind(window.performance);else\nreturn function(){return new Date().getTime();};})();var requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60);};})().bind(window);window.__RafRecorder={frames:[],flush:true,record:function(timeStamp){if(__RafRecorder.flush){__RafRecorder.frames=[];__RafRecorder.flush=false;}\n__RafRecorder.frames.push(timeStamp);requestAnimationFrame(__RafRecorder.record);},get:function(){__RafRecorder.flush=true;return __RafRecorder.frames;}};requestAnimationFrame(window.__RafRecorder.record);}());")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 95 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'MIAPG1405200057', ip: '10.212.68.84', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_25'
Session ID: f4697214-f15d-4b66-b54a-1a97a709ab12
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=9, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:27622/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
   Stacktrace:
     Error: [execute("(function(){var getTimeMs=(function(){if(window.performance)\nreturn(performance.now||performance.mozNow||performance.msNow||performance.oNow||performance.webkitNow).bind(window.performance);else\nreturn function(){return new Date().getTime();};})();var requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60);};})().bind(window);window.__RafRecorder={frames:[],flush:true,record:function(timeStamp){if(__RafRecorder.flush){__RafRecorder.frames=[];__RafRecorder.flush=false;}\n__RafRecorder.frames.push(timeStamp);requestAnimationFrame(__RafRecorder.record);},get:function(){__RafRecorder.flush=true;return __RafRecorder.frames;}};requestAnimationFrame(window.__RafRecorder.record);}());")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 95 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'MIAPG1405200057', ip: '10.212.68.84', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_25'
Session ID: f4697214-f15d-4b66-b54a-1a97a709ab12
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=9, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:27622/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
    at exports.newError (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\browser-perf\node_modules\wd\lib\utils.js:139:13)
    at C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\browser-perf\node_modules\wd\lib\callbacks.js:75:19
    at C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\browser-perf\node_modules\wd\lib\webdriver.js:174:5
    at Request._callback (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\browser-perf\node_modules\wd\lib\http-utils.js:85:7)
    at Request.self.callback (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:364:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:1318:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:1266:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
==== async task ====
    at [object Object].start (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\lib\index.js:50:54)
    at [object Object].<anonymous> (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\performance.js:18:14)
    at C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\jasminewd\index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1518:8)
==== async task ====
Asynchronous test function: it()
    at [object Object].<anonymous> (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\jasminewd\index.js:93:33)
    at [object Object].<anonymous> (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\minijasminenode\lib\async-callback.js:45:37)
    at [object Object].jasmine.Block.execute (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1174:17)
    at [object Object].jasmine.Queue.next_ (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2209:31)
    at [object Object]._onTimeout (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2199:18)
Error
    at [object Object].<anonymous> (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\performance.js:10:5)
    at [object Object].jasmine.Env.describe_ (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:913:21)
    at [object Object].jasmine.Env.describe (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:898:15)
    at describe (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\node_modules\protractor-perf\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
    at Object.<anonymous> (C:\Users\majgotra\sambuca-ta\sambuca-qa\tools\SCT_Automation\performance.js:8:1)

Finished in 2.006 seconds
1 test, 1 assertion, 1 failure

Process finished with exit code 1

**Comment by axemclion** [comment]
Wow, that looks weird. Not sure what is going on. Can you try running http://github.com/axemclion/browser-perf directly against IE driver? Do you get the same error?

**Comment by axemclion** [comment]
Closing issue since we have no more updates, and not enough info to investigate.
