### ISSUE TITLE
Are there specific version combinations of protractor / chrome etc required?

### ISSUE THREAD

**Issue by oldtinroof** [axemclion/protractor-perf#38]
I'm trying to get this running with unfortunately fairly locked down versions of protractor, webdriver, and chrome (corporate dev environment ftw).

I'm running Protractor 3.3.0, wd 0.4.0, and Chrome 35 (:o).

When I try to run the prefRunner.start(); I get:

`Message:
    Failed: [logTypes()] Not JSON response
  Stack:
    Error: [logTypes()] Not JSON response
        at exports.newError (C:\dev\myapp\node_modules\wd\lib\utils.js:139:13)
        at C:\dev\myapp\node_modules\wd\lib\callbacks.js:59:17
        at C:\dev\myapp\node_modules\wd\lib\webdriver.js:174:5
        at Request._callback (C:\dev\myapp\node_modules\wd\lib\http-utils.js:87:7)
        at Request.self.callback (C:\dev\myapp\node_modules\wd\node_modules\request\request.js:368:22)
        at emitTwo (events.js:87:13)
        at Request.emit (events.js:172:7)
        at Request.<anonymous> (C:\dev\myapp\node_modules\wd\node_modules\request\request.js:1219:14)
        at emitOne (events.js:82:20)
        at Request.emit (events.js:169:7)
        at IncomingMessage.<anonymous> (C:\dev\myapp\node_modules\wd\node_modules\request\request.js:1167:12)
        at emitNone (events.js:72:20)
        at IncomingMessage.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:905:12)
        at nextTickCallbackWith2Args (node.js:455:9)
        at process._tickCallback (node.js:369:17)
`

I can't find what's causing this - I've had a poke about in the stack, but nothing obvious is jumping out.  Am I missing something straighforward?

**Comment by axemclion** [comment]
Are you able to run just protractor ? You would need a fairly modern Chrome, but that should be it. Could you try running browser-perf directly and see if that also fails ?

**Comment by oldtinroof** [comment]
Ah the wonders of working in a corporate dev environment - it turns out to be the proxy blocking the requests to the selenium that fired up on my IP address rather than localhost.

Managed to fix it now, thanks for getting back to me so quickly!

**Comment by axemclion** [comment]
@oldtinroof Thanks ... glad it worked out.
