### ISSUE TITLE
Cannot find module 'node_modules/protractor/built/configParser'

### ISSUE THREAD

**Issue by jahnavi310** [axemclion/protractor-perf#40]
this was working fine till yest but now i see this:

```
Cannot find module 'node_modules/protractor/built/configParser'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (..../node_modules/protractor-perf/lib/cli.js:145:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

```

any idea why this could be happening?

**Comment by axemclion** [comment]
Did protractor move the config parser ?

**Comment by jahnavi310** [comment]
i just updated protractor to the latest version 4.0.7

**Comment by jahnavi310** [comment]
also now for some reason when i do protractor-perf it does not enter the onprepare...

**Comment by jahnavi310** [comment]
also it doesnt seem like ptor hasnt moved it

**Comment by jahnavi310** [comment]
there is a difference in the stack trace when i run the tests with protractor.conf.js as opposed to protractor-perf.js.

Any idea why this would be happening/

**Comment by jahnavi310** [comment]
this is resolved

**Comment by matteoPhre** [comment]
how was this issue resolved?

**Comment by wick3dshadow** [comment]
Hi @jahnavi310 / @axemclion 

I am getting the error "Cannot find module 'protractor/lib/configParser'".
Any inputs why would I be getting this and how to resolve?
