### ISSUE TITLE
Unsupported OS/browser/version/device combo: OS: 'Windows 2003', Browser: 'googlechrome', Version: '54.', Device: 'unspecified'

### ISSUE THREAD

**Issue by premkh9** [axemclion/protractor-perf#46]
Hi Parshuram,

I am trying to execute one of my script in saucelabs in windows 7 platform and 54th version of chome. But observing below mentioned error. If I dont specify version and platform details , its trying to execute the script in windows XP and 49 version of chrome. Saucelabs team asked me to reach out to you as they are not sure, how this plugin/library is implemented. It would be much appreciated, if you can help us. 

This is working as expected locally. Even in sauce labs but not with platform and version details. 
Tried with different platforms and versions as well and observing same error.

capabilities: {
		'browserName': 'chrome',
		'parent-tunnel': "chi_master",
	        'platform': 'Windows 7',
	        'version':'54'
	      },

Error Details - 

[16:26:28] I/sauce - Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[16:26:28] I/launcher - Running 1 instances of WebDriver
[16:26:28] E/launcher - Unsupported OS/browser/version/device combo: OS: 'Windows 2003', Browser: 'googlechrome', Version: '54.', Device: 'unspecified'
[16:26:28] E/launcher - UnsupportedOperationError: Unsupported OS/browser/version/device combo: OS: 'Windows 2003', Browser: 'googlechrome', Version: '54.', Device: 'unspecified'
    at WebDriverError (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:10)
    at UnsupportedOperationError (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:448:10)
    at parseHttpResponse (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:552:11)
    at C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:472:11
    at ManagedPromise.invokeCallback_ (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25
    at C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:369:9)
[16:26:28] E/launcher - Process exited with error code 199

![image](https://cloud.githubusercontent.com/assets/14880073/22314083/05fe2494-e31d-11e6-848a-fef6523dedef.png)

**Comment by axemclion** [comment]
Can you try using the `wd` node library and see if you can run the device you are looking for ? You should see examples on the website of saucelabs.

**Comment by premkh9** [comment]
Hi Ram, I tried using the wd node as well observing the same error. I am trying to run on windows browser not on any particular device. Yes I am using sauce lab platform configurator to add platform details. We have regular scripts which executes perfectly on sauce labs on all platforms without any issue. This is observed only when we are using protractor-perf followed by configuration file

**Comment by axemclion** [comment]
Can you add teh sauce labs scripts that work well ? I could derive the configuration for protractor-perf here from that.

**Comment by premkh9** [comment]
Hi Ram, Below configuration works well in sauce labs for protractor. You can use the same. 
You can just create a simple script (login to google) or use the example script of protractor test(provided by GIt hub community, when you install protractor ) and try to execute in sauce labs. Let me know, if you need our sauce credentials 

capabilities: {
'browserName': 'chrome',
'platform': 'Windows 7',
'version':'54'
},

**Comment by harsha698** [comment]
Hello, I am facing the same problem. Here are the details:
selenium webdriver
caps = DesiredCapabilities.safari();
caps.setCapability("name", "Safari Browser");
caps.setCapability("version", "11");
caps.setCapability("platform", "macOS High Sierra");
caps.setCapability("tunnelIdentifier", tunnelName);

With this am getting exception while running tests in saucelabs:
Error occurred: (class org.openqa.selenium.WebDriverException): Unable to parse remote response: Misconfigured -- Unsupported OS/browser/version/device combo: OS: 'OS X 10.9', Browser: 'safari', Version: '12.', Device: 'unspecified' (ExceptionLogger:20)
