### ISSUE TITLE
Running the protractor perf test example results in  Failed: [logTypes()] Not JSON response

### ISSUE THREAD

**Issue by songokudbz** [axemclion/protractor-perf#47]
Can someone help with this?
{code}
$ protractor-perf protractor-perf.conf.js
[13:17:08] I/direct - Using ChromeDriver directly...
[13:17:08] I/launcher - Running 1 instances of WebDriver
Started
Here
F

Failures:
1) angularjs homepage todo list should add a todo
  Message:
    Failed: [logTypes()] Not JSON response
  Stack:
    Error: [logTypes()] Not JSON response
        at exports.newError (D:\dev\sims-e2e-test\node_modules\wd\lib\utils.js:139:13)
        at D:\dev\sims-e2e-test\node_modules\wd\lib\callbacks.js:59:17
        at D:\dev\sims-e2e-test\node_modules\wd\lib\webdriver.js:174:5
        at Request._callback (D:\dev\sims-e2e-test\node_modules\wd\lib\http-utils.js:87:7)
        at Request.self.callback (D:\dev\sims-e2e-test\node_modules\wd\node_modules\request\request.js:368:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (D:\dev\sims-e2e-test\node_modules\wd\node_modules\request\request.js:1219:14)
        at emitOne (events.js:101:20)
        at Request.emit (events.js:188:7)
{code}

**Comment by axemclion** [comment]
Can you set an environment variable called `DEBUG` and run the examples ? The log should have more information about why it failed.

**Comment by renovatorruler** [comment]
@axemclion I'm also having the same problem. I believe the problem is related to Chrome version 55 onwards. My other machine with Chrome 53 works fine.

**Comment by jimitpatel9** [comment]
@axemclion I'm also having the same problem. I think the problem is related to Chrome version. I am currently having Chrome version 56 and it fail and on my other machine I have Chrome 53 and it works.

**Comment by songokudbz** [comment]
Hi axemclion,

sorry I've deleted my configuration and do not have time today to reproduce this. Maybe over the weekend I will have a look at this DEBUG variable.

**Comment by jimitpatel9** [comment]
@axemclion 
Can you take look into these error?
I am having Chrome version 56.

Failures:
1) angularjs homepage todo list should add a todo
  Message:
    Failed: [logTypes()] Not JSON response
  Stack:
    Error: [logTypes()] Not JSON response
        at exports.newError (C:\Users\work\protractor-perf\node_modules\wd\lib\utils.js:139:13)
        at C:\Users\work\protractor-perf\node_modules\wd\lib\callbacks.js:59:17
        at C:\Users\work\protractor-perf\node_modules\wd\lib\webdriver.js:174:5
        at Request._callback (C:\Users\work\protractor-perf\node_modules\wd\lib\http-utils.js:87:7)
        at Request.self.callback (C:\Users\work\protractor-perf\node_modules\wd\node_modules\request\request.js:368:22)
        at emitTwo (events.js:87:13)
        at Request.emit (events.js:172:7)
        at Request.<anonymous> (C:\Users\work\protractor-perf\node_modules\wd\node_modules\request\request.js:1219:14)
        at emitOne (events.js:82:20)
        at Request.emit (events.js:169:7)
    From: Task: <anonymous>
        at null.start (C:\Users\work\protractor-perf\lib\index.js:51:37)
        at Object.<anonymous> (C:\Users\work\protractor-perf\test\example.spec.js:7:14)
        at C:\Users\work\protractor-perf\node_modules\jasminewd2\index.js:94:23
        at new ManagedPromise (C:\Users\work\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:1082:7)
        at controlFlowExecute (C:\Users\work\protractor-perf\node_modules\jasminewd2\index.js:80:18)
        at TaskQueue.execute_ (C:\Users\work\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2913:14)
        at TaskQueue.executeNext_ (C:\Users\work\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2896:21)
        at C:\Users\work\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2820:25
        at C:\Users\work\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:639:7
        at process._tickCallback (node.js:369:9)
    From: Task: Run it("should add a todo") in control flow
        at Object.<anonymous> (C:\Users\work\protractor-perf\node_modules\jasminewd2\index.js:79:14)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\Users\work\protractor-perf\test\example.spec.js:5:2)
        at Object.<anonymous> (C:\Users\work\protractor-perf\test\example.spec.js:2:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

**Comment by ghost** [comment]
@axemclion Thanks for the great module. It worked last night but not sure  I'm facing the same issue 'Not JSON response' now. Any help would be greatly appreciate.

[22:10:07] E/launcher - [logTypes()] Not JSON response
[22:10:07] E/launcher - Error: [logTypes()] Not JSON response
    at exports.newError (/Users/uix326/Documents/ease_automation/easePro/node_modules/wd/lib/utils.js:139

:13)
    at /Users/uix326/Documents/ease_automation/easePro/node_modules/wd/lib/callbacks.js:59:17
    at /Users/uix326/Documents/ease_automation/easePro/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/Users/uix326/Documents/ease_automation/easePro/node_modules/wd/lib/http-utils.
js:87:7)

**Version Details**
protractor - 5.1.1
protractor-perf-0.2.3
chrome browser 57
chrome driver - 2.28
selenium-standalone - 6.0.1
web driver-manager - 12.0.3

**Comment by ghost** [comment]
@axemclion more details here about the issue when I run from office vpn 

bp:metrics Initializing Metrics +3s
  bp:probes Registering probe PerfLogProbe +129ms
  bp:probes:AndroidTracingProbe Initialize +1ms
  bp:probes Registering probe AndroidTracingProbe +0ms
  bp:probes Registering probe PerfLogProbe +3ms
  bp:probes Registering probe AndroidTracingProbe +0ms
  bp:probes Registering probe RafBenchmarkingProbe +1ms
  bp:probes Registering probe NavTimingProbe +2ms
  bp:probes Registering probe NetworkResourcesProbe +2ms
  bp:metrics TimelineMetrics setup called +3ms
  bp:metrics ChromeTracingMetrics setup called +2ms
  bp:metrics NetworkResources setup called +0ms
  bp:probes setup +1ms
  bp:probes PerfLogProbe setup called +0ms
  bp:probes AndroidTracingProbe setup called +1ms
  bp:probes NetworkResourcesProbe setup called +0ms
  bp:probes start +5ms
  bp:probes PerfLogProbe start called +0ms
  bp:selenium:runner CALL logTypes()  +2ms
[01:14:19] E/launcher - [logTypes()] Not JSON response
[01:14:19] E/launcher - Error: [logTypes()] Not JSON response

@songokudbz @prashantpawar @jimitpatel9 @henriquelbsouza  please help me if you have any idea about this issue ?

**Comment by deepu105045** [comment]
I am also getting same error

[16:09:38] E/launcher - [logTypes()] Not JSON response
[16:09:38] E/launcher - Error: [logTypes()] Not JSON response
    at exports.newError (/Users/XXXX/Documents/protractorPerf/XXX/node_modules/wd/lib/utils.js:139:13)
 
browser version : Version 57.0.2987.133 (64-bit)
selenium/chromedriver_2.28

**Comment by brengracel** [comment]
Is this issue still open? Or anyone make this work?

**Comment by KapilKasar** [comment]
As per my observation, it does not work when directConnect set to true, rather start the driver manually and set directConnect:false, then it worked for me.
