### ISSUE TITLE
Failed: Cannot read property 'fulfilled' of undefined

### ISSUE THREAD

**Issue by saxena-ashutosh** [axemclion/protractor-perf#50]
I am trying to use protractor-perf with angular2 project with typescript and faced below error on perf.start() statement in my test spec:
× should display panel with user input
- Failed: Cannot read property 'fulfilled' of undefined
          at ProtractorPerf.<anonymous> (E:\test-proj\node_modules\protractor-perf\lib\index.js:43:34)
          at ManagedPromise.invokeCallback_ (C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:1379:14)
          at TaskQueue.execute_ (C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2913:14)
          at TaskQueue.executeNext_ (C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2896:21)
          at asyncRun (C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2820:25)
          at C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:639:7
          at process._tickCallback (internal/process/next_tick.js:109:7)
      From: Task: <anonymous>
          at ProtractorPerf.start (E:\test-proj\node_modules\protractor-perf\lib\index.js:51:37)
          at Object.<anonymous> (E:\test-proj\e2e\app.e2e-spec.ts:13:20)
          at new ManagedPromise (C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:1082:7)
          at TaskQueue.execute_ (C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2913:14)
          at TaskQueue.executeNext_ (C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2896:21)
          at asyncRun (C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:2820:25)
          at C:\Users\username\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\selenium-webdriver\lib\promise.js:639:7
          at process._tickCallback (internal/process/next_tick.js:109:7)

I have initialized and used protracter-perf  inside our test spec using following statements:

var PerfRunner = require('protractor-perf');

describe('test-proj App', () => {
  var perfRunner = new PerfRunner('protractor', browser);
it('should display panel with user input', () => {
  perfRunner.start();
page.navigateTo();
    expect(page.getInputsCount()).toEqual(3);
    perfRunner.stop();
}

Can anyone help me on this.

Thanks
Ashutosh

**Comment by markserbol** [comment]
Having the same issue in typescript. Anyone solved this?
